@startuml
title Diagrama de Contêiner - LavCust

left to right direction

actor "Produtor Rural" as Usuario

rectangle "Navegador Web\n(Chrome, Edge, Firefox)" as Browser

rectangle "Interface Web\n(HTML/CSS)" as Frontend

rectangle "Backend\n(Python + Flask)" as Backend

database "Banco de Dados\n(SQLite)" as BD

Usuario --> Browser : Acessa o sistema

Browser --> Frontend : Exibe as páginas

Frontend --> Backend : Envia requisições

Backend --> BD : Salva e consulta dados

BD --> Backend : Retorna informações

Backend --> Frontend : Exibe resultados

Frontend --> Browser : Mostra informações

@enduml
