@startuml contexto
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

TITLE Diagrama de Contexto - Sistema LavCust (C4 Nível 1)

Person(produtor, "Produtor Rural", "Acompanha relatórios financeiros e custos de produção.")
Person(admin, "Administrador da Fazenda", "Gerencia dados operacionais, insumos e lançamentos de custos.")

System(lavcust, "Sistema LavCust", "Sistema de gestão e apuração de custos operacionais da lavoura.")

SystemDb(bd, "Banco de Dados", "Armazena informações sobre a fazenda, usuários e custos.")

Rel(produtor, lavcust, "Consulta relatórios e indicadores", "HTTPS / Web")
Rel(admin, lavcust, "Cadastra dados, insumos e despesas", "HTTPS / Web")
Rel(lavcust, bd, "Lê e grava informações", "SQL / TCP")

@enduml
